### ISSUE TITLE
Relapse/Don't Know not a valid choice

### ISSUE THREAD

**Issue by southalln** [tsheils/project_cure_issues#69] opened 2017-04-27 15:12 UTC
POST to https://api-dev.emochacure.com/v1/reports getting a 400 Bad Request
{"relapse":["\"Don’t Know\" is not a valid choice."]}

Here's what I POSTed {"status":"Submitted","disease":285,"why_new_way":[{"answer":"Patient failed previous therapy"}],"use_drug":[{"answer":"To treat a disease other than the one for which the drug is approved"}],"outcome":"Unknown/Not yet determined","regimens":[{"drug":9560,"drugName":"paracetamol"},{"drug":7473,"drugName":"disulfiram"}],"site_of_infection":[],"specific_site":[],"organisms":[],"how_diagnosis":[],"resistant_drugs":[],"combo_drugs":[],"how_outcome":[{"answer":"Clinical assessment"}],"when_outcome":"After a period of follow-up","how_long_time":24,"how_long_unit":"Weeks","relapse":"Don’t Know","reminder":false,"anonymous":true}

**Comment by emochaadmin** [comment] 2017-04-28 19:03
Duplicate of 66?

**Comment by tsheils** [comment] 2017-05-01 14:14
"don't know is not very helpful user input

**Comment by southalln** [comment] 2017-05-01 14:19
Nevertheless, it is allowed by the form - schema should allow this

**Comment by tsheils** [comment] 2017-05-01 14:57
New question to check with Heather is if we even want to keep it on the form.

**Closed as completed** 2017-05-16 19:50 UTC
Labels: critical, check with heather, LGTM
